### ISSUE TITLE
Servoy 2023.12.2.3924 not supported

### ISSUE THREAD

**Issue by r4inX** [itechpros/servoy-war-builder#2]
Hey Guys,

i just noticed that the pipeline is not working anymore. 
I think the latest Servoy-Release is not supported.

We´re using Servoy 2023.12.2.3924.
Tried to modify my pipeline with the following:

```
  steps:
    - step: &war-build
        name: WAR Build
        script:
          - pipe: docker://itechpros/servoy-war-builder:latest
            variables:
              SERVOY_VERSION: 2023.12.2.3924
```

Tried :0.2.0, 0.3.3 and .latest. All of those are not working anymore.

Greetings
